version: '3.8'

services:
  backend:
    build: ./backend
    image: sitharaka/devops-backend:latest
    restart: always
    ports:
      - "3001:3000"
    environment:
      - MONGO_URI=mongodb+srv://Admin:RJPTG25fUYFpyJpA@cluster0.zunewah.mongodb.net/devops

  frontend:
    build: ./frontend
    image: sitharaka/devops-frontend:latest
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

